### ISSUE TITLE
Bug in NVT.java on backspace

### ISSUE THREAD

**Issue by personalsoft-fabianobonin** [teverett/ktelnet#49]
Hi,

NVT.java, line 341.

```java
  String str = baos.toString(charsetUTF8.name());
  baos = new ByteArrayOutputStream();
  str = str.substring(0, str.length() - 1);
  if (str.length() > 0) {
     baos.write(str.getBytes(), 0, str.length());
  }
  // echo the BS/DEL back
  if (isEcho()) {
     write(b);
  }
```

If we call nvt.readln() and the first key pressed is a KEY_BS or KEY_DEL, "str" will contain an empty String and `str.substring(0, str.length() - 1)` will evaluate to `str.substring(0, -1)`, which will throw an exception.

A simple check would avoid this:

```java
  String str = baos.toString(charsetUTF8.name());
  if (str.length() > 0) {
    baos = new ByteArrayOutputStream();
    str = str.substring(0, str.length() - 1);
    if (str.length() > 0) {
       baos.write(str.getBytes(), 0, str.length());
    }
    // echo the BS/DEL back
    if (isEcho()) {
       write(b);
    }
  }
```

Don't know if this project is active, but I can create a PR if needed.

Regards,

Fabiano

**Comment by teverett** [comment]
Hello @personalsoft-fabianobonin thanks for this.  The project is active, and a PR would be welcome.  You are also welcome to add your name to the pom.xml file.

**Comment by teverett** [comment]
@personalsoft-fabianobonin Thanks! I believe this is fixed on line 242 of NVTStreamImpl.java
