### ISSUE TITLE
Pushed artifact jar contains dependencies

### ISSUE THREAD

**Issue by ocervinka** [teverett/ktelnet#79]
The Maven build seems to be configured to create and publish fat jar which includes classes from all dependencies (`logback`, `apache.commons.cli`, `slf4j`). Flat jar is handy when running the Telnet server directly from the jar as no extra dependencies needs to be added to classpath. However, it causes problems when using the Telnet server as a library. Can we publish a jar with compiled classes only?

**Comment by teverett** [comment]
@ocervinka fixed.  thank-you for submitting the issue.
